addons/urls.py
from django.urls import path
from addons import views

app_name = "addons"

urlpatterns = [
    path("contact_us/", views.contact_us, name="contact_us"),
    path("about_us/", views.about_us, name="about_us"),
    path("send_faq_qs/", views.send_faq_qs, name="send_faq_qs"),
    path("subscribe_to_newsletter/", views.subscribe_to_newsletter, name="subscribe_to_newsletter"),
    path("privacy_terms_condition/", views.privacy_terms_condition, name="privacy_terms_condition"),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<slug>/', views.category_detail, name="category_detail"),
    path('<pid>', views.blogDetail, name="blog-detail"),

]

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("my-dashboard/", views.buyer_account, name="buyer-dashboard"),
    path("profile/", views.buyer_profile, name="profile"),
    path("settings/", views.buyer_profile_settings, name="settings"),
    path("my-orders/", views.buyer_orders, name="buyer-orders"),
    path("my-orders/<oid>/", views.buyer_order_detail, name="buyer-order-detail"),

    # Shipping Address
    path("my-address/", views.buyer_address, name="buyer-address"),
    path("welcome-address/", views.buyer_welcome_address, name="buyer_welcome_address"),
    path("my-address/edit/<id>/", views.buyer_edit_address, name="buyer-edit-address"),
    path("my-address/delete/<id>/", views.buyer_delete_address, name="buyer-delete-address"),

    # Billing Address
    path("my-billing-address/", views.buyer_billing_address, name="buyer-billing-address"),
    path("my-billing-address/edit/<id>/", views.buyer_edit_billing_address, name="buyer-edit-billing-address"),
    path("add_billing_address", views.add_billing_address, name="add_billing_address"),
    path("my-billing-address/delete/<id>/", views.buyer_delete_billing_address, name="buyer_delete_billing_address"),

    path("my-wishlist/", views.buyer_wishlist, name="buyer-wishlist"),
    path("my-invoices/", views.buyer_invoices, name="buyer-invoices"),
    path("my-invoice/<oid>/", views.buyer_invoice_detail, name="buyer-invoice-detail"),
    path("my-bids/", views.buyer_bids, name="buyer_bids"),
    path("my-bids-detail/<pid>/<bid>", views.buyer_bids_detail, name="buyer_bids_detail"),
    path("order-tracker/", views.buyer_track_order, name="order-tracker"),
    path("tracked-order/<oid>/", views.tracked_order, name="tracked-order"),
    path("buyer_offer", views.buyer_offer, name="buyer_offer"),
    path("buyer_offer_detail/<pid>/<oid>/", views.buyer_offer_detail, name="buyer_offer_detail"),
    path("cancel_order/<oid>/", views.cancel_order, name="cancel_order"),
    path("cancel_orderitem/", views.cancel_orderitem, name="cancel_orderitem"),

    # Messaging
    path('inbox/', views.inbox, name="buyer_message"),
    path('inbox/<username>/', views.get_inbox, name="inbox-detail"),
    path('send_message_ajax/<username>/', views.send_message_ajax, name="send_message_ajax"),
    path('search_user/', views.search_users, name="search_users"),

    # Ajax
    path("delete-wishlist/<id>/", views.delete_from_wishlist, name="delete-wishlist"),
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),
    path("make-default-address/", views.make_address_default, name="make-default-address"),
    path("make-billing-default-address/", views.make_billing_address_default, name="make-default-billing-address"),

]

ecommerce_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('user/', include("userauths.urls")),
    path('b/', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('base/', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from store import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="home"),
    path("homemain/", views.indexmain, name="homemain"),
    path("welcome/", views.welcome, name="welcome"),
    path("offer/", views.offer, name="offer"),
    path("category/", views.category_list, name="category"),
    path("shop/", views.shop, name="shop"),
    path("hot_deals/", views.hot_deals, name="hot_deals"),
    path("search/", views.search_list, name="search"),
    path("detail/<slug:slug>/", views.product_detail, name="product-detail"),
    path("my-cart/", views.cart_view, name="cart-view"),
    path("category/<cid>/", views.category_detail, name="category_detail"),
    path("shipping_address/", views.shipping_address, name="shipping_address"),
    path("checkout/<oid>/", views.checkout_view, name="checkout"),
    path("custom-checkout/<oid>/", views.custom_checkout_view, name="checkout2"),
    path('checkout/order-detail/<id>/', views.PaymentConfirmation.as_view(), name='order-detail'),
    path('success-payment/', views.PaymentSuccessView, name='success'),
    path('failed-payment/', views.PaymentFailedView, name='failed'),
    
    # Bidding and Auctioon
    path("auction/", views.auction, name="auction"),
    path("auction_detail/<pid>/", views.auction_detail, name="auction_detail"),
    path("auction_update/<pid>/<bid>/", views.auction_update, name="auction_update"),
    
    # Paypal
    path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-completed/<oid>/", views.payment_completed_view, name="payment-completed"),
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

    # Ajax URLs
    path("ajax/add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("ajax/helpful-review/", views.helpful_review, name="helpful-review"),
    path("ajax/add-review/<int:pid>/", views.add_review, name="add-review"),
    path("ajax/ask-question/", views.ask_question, name="ask-question"),
    path('ajax/update-cart/',views.update_cart,name='update-cart'),
    path('ajax/delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),

    # API URLs
    path('api/checkout-session/<id>/', views.create_checkout_session, name='api_checkout_session'),
    path('country_get/', views.country_get, name='country_get'),


]

userauths/urls.py
from django.urls import path
from userauths import views
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500


app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.Register, name="sign-up"),
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    path("sign-in-2/", views.loginView, name="sign-in-2"),
    path("sign-out/", views.logoutView, name="sign-out"),
    path("vendor_sign_in/", views.loginAsVendor, name="vendor_sign_in"),
    path("check_email/", views.check_email, name="check_email"),
    
    
]

store/forms.py
from store.models import Review, CartOrderItem, CartOrder
from core.models import Address, BillingAddress
from django import forms

class ReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Write review"}))

    class Meta:
        model = Review
        fields = ['review', 'rating']


class AddressForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    mobile = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    town_city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    zip = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)

    class Meta:
        model = Address
        fields = ['full_name','mobile','email','country' ,'state','town_city','zip','address', 'same_as_billing_address']


class BillingAddressForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    mobile = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    town_city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    zip = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':''}), required=True)

    class Meta:
        model = BillingAddress
        fields = ['full_name','mobile','email','country','state','town_city','zip','address']
        
        
        
class CartOrderItemForm(forms.ModelForm):
    tracking_id = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Enter Tracking ID'}))


    class Meta:
        model = CartOrderItem
        fields = ['delivery_couriers', 'tracking_id']
        
        
class CheckoutForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Full Name'}), required=False)
    mobile = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Active Mobile Number'}), required=False)
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Valid Email Address'}), required=False)
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'State'}), required=False)
    town_city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Town or City'}), required=False)
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Street and Home Address'}), required=False)

    billing_state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Billing State'}), required=False)
    billing_town_city = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':'Billing Town or City'}), required=False)
    billing_address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'id': "", 'placeholder':' Billing Street and Home Address'}), required=False)

    class Meta:
        model = CartOrder
        fields = ['full_name','mobile','email','country','state','town_city','address', 'postal_code' ,'billing_state','billing_town_city','billing_address', 'billing_postal_code' ,'billing_country']
        

templates/store/ffless/navbar.html
    
{% load static %}


<div class="vs-menu-wrapper">
    <div class="vs-menu-area">
      <button class="vs-menu-toggle">
        <i class="fal fa-times"></i>
      </button>
      <div class="mobile-logo">
        <a href="index.html">
          <img src="{% static 'assets/img/foodforless.png' %}" alt="foodforless">
        </a>
      </div>
      <div class="vs-mobile-menu link-inherit"></div>
    </div>
  </div>
  <div class="sidemenu-wrapper d-none d-lg-block">
    <div class="sidemenu-content">
      <button class="closeButton border-theme text-theme bg-theme-hover sideMenuCls">
        <i class="far fa-times"></i>
      </button>
      <div class="widget widget_shopping_cart">
        <h3 class="widget_title">Shopping cart</h3>
        <div class="widget_shopping_cart_content">
          <ul class="cart_list">
            <li class="mini_cart_item">
              <a href="shop.html" class="remove">
                <i class="fal fa-trash-alt"></i>
              </a>
              <a href="shop.html">
                <img src="{% static 'assets/img/cart/cart-img-1-1.jpg' %}" alt="Cart Image">Hot Burger </a>
              <span class="quantity">1 × <span class="amount">
                  <span>$</span>40.00 </span>
              </span>
            </li>
            <li class="mini_cart_item">
              <a href="shop.html" class="remove">
                <i class="fal fa-trash-alt"></i>
              </a>
              <a href="shop.html">
                <img src="{% static 'assets/img/cart/cart-img-1-2.jpg' %}" alt="Cart Image">Vegetable </a>
              <span class="quantity">1 × <span class="amount">
                  <span>$</span>99.00 </span>
              </span>
            </li>
            <li class="mini_cart_item">
              <a href="shop.html" class="remove">
                <i class="fal fa-trash-alt"></i>
              </a>
              <a href="shop.html">
                <img src="{% static 'assets/img/cart/cart-img-1-3.jpg' %}" alt="Cart Image">Pop Pizza </a>
              <span class="quantity">1 × <span class="amount">
                  <span>$</span>56.00 </span>
              </span>
            </li>
            <li class="mini_cart_item">
              <a href="shop.html" class="remove">
                <i class="fal fa-trash-alt"></i>
              </a>
              <a href="shop.html">
                <img src="{% static 'assets/img/cart/cart-img-1-4.jpg' %}" alt="Cart Image">Onion & Tomato </a>
              <span class="quantity">1 × <span class="amount">
                  <span>$</span>23.00 </span>
              </span>
            </li>
            <li class="mini_cart_item">
              <a href="shop.html" class="remove">
                <i class="fal fa-trash-alt"></i>
              </a>
              <a href="shop.html">
                <img src="{% static 'assets/img/cart/cart-img-1-5.jpg' %}" alt="Cart Image">Cool Drinks </a>
              <span class="quantity">1 × <span class="amount">
                  <span>$</span>100.00 </span>
              </span>
            </li>
          </ul>
          <p class="total">
            <strong>Subtotal:</strong>
            <span class="amount">
              <span>$</span>318.00 </span>
          </p>
          <p class="buttons">
            <a href="cart.html" class="vs-btn">View cart</a>
            <a href="checkout.html" class="vs-btn">Checkout</a>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="popup-search-box d-none d-lg-block">
    <button class="searchClose border-theme text-theme">
      <i class="fal fa-times"></i>
    </button>
    <form 
    action="{% url 'store:search' %}" method="GET" class="form-search">
      <input type="text" class="border-theme" name="q" placeholder="What are you looking for">
      <button type="submit">
        <i class="fal fa-search"></i>
      </button>
    </form>

  </div>
  <header class="header-wrapper header-layout6">
    <div class="header-top">
      <div class="container">
        <div class="row align-items-center justify-content-between">
          <div class="col-auto d-none d-lg-block">
            <div class="header-infos">
              <p class="info">
                <img src="{% static 'assets/img/icons/info-icon-2.png' %}" alt="icon">Free express delivery + Easy returns
              </p>
            </div>
          </div>
          <div class="col-lg-auto text-center text-lg-end">
            <div class="header-infos">
              <p class="info">
                <i class="fas fa-phone-alt"></i>Phone: <a href="tel:254700061030">+254700061030</a>
              </p>
              <p class="info d-none d-md-inline-block">
                <i class="fas fa-envelope"></i>Email: <a href="mailto:info@yummytummy.co.ke">info@yummytummy.co.ke</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="menu-area">
        <div class="row align-items-center justify-content-between">
          <div class="col col-lg-auto">
            <div class="header-logo">
              <a href="index.html">
                <img src="{% static 'assets/img/foodforless.png' %}" alt="foodforless">
              </a>
            </div>
          </div>
          <div class="col-auto">
            <nav class="main-menu mobile-menu-active menu-style2">
              <ul>
                <!-- <li>
                  <a href="{% url 'store:homemain' %}">Home</a>
                </li> -->
                <li>
                  <a href="{% url 'store:shop' %}">Shop</a>
                </li>

            
      
                
                <li class="menu-item-has-children">
                  <a href="">About us</a>
                  <ul class="sub-menu">
                    <li>
                      <a href="{% url 'addons:about_us' %}">FAQS</a>
                    </li>
                <li>
                  <a href="{% url 'addons:about_us' %}">Who we are</a>
                </li>
                <li>
                  <a href="{% url 'addons:about_us' %}">Our Process</a>
                </li>
                <li><a href="{% url 'addons:about_us' %}">why Yummy Tummy</a>
                </li>
                <li><a href="{% url 'addons:contact_us' %}">Reach us</a>
                </li>
                <li><a href="{% url 'blog:blog-list' %}">Blogs</a>
                </li>
                <li><a href="{% url 'addons:contact_us' %}">Careers</a>
                </li>
                    
                  </ul>
                </li>
                
                {% if request.user.is_authenticated %}
                <li class="menu-item-has-children">
                  <a href="">Dashboard</a>
                  <ul class="sub-menu">
                    <li>
                      <a href="{% url 'core:buyer-dashboard' %}"> My account</a>
                    </li>
                 
                    
                  </ul>
                </li>
                {% else %}
              
                <li class="menu-item-has-children">
                  <a href="">Sign In</a>
                  <ul class="sub-menu">
                    <li>
                      <a href="{% url 'userauths:sign-in' %}">Login</a>
                    </li>
                    <li>
                      <a href="{% url 'userauths:sign-up' %}">Register</a>
                    </li>
                    
                  </ul>
                </li>
                {% endif %}
                
                {% if request.user.profile.seller == True %}
                <li class="visible_list">
                  <a href="{% url 'vendor:dashboard' %}"
                    ><span class="title">Vendor Dashboard</span></a
                  >
                </li>
                {% else %}
                <li class="visible_list">
                  <a href="{% url 'vendor:become-vendor' %}"
                    ><span class="title">Become a Vendor</span></a
                  >
                </li>
                {% endif %}

           
              </ul>
            </nav>
          </div>
          <div class="col-auto d-none d-sm-block">
            <div class="header-buttons">
              <button type="button" class="searchBoxTggler">
                <i class="far fa-search"></i>
              </button>
              <a href="{% url 'core:buyer-wishlist' %}">
                <i class="fal fa-heart"></i>
              </a>
          
              <a href="{% url 'store:cart-view' %}">
                <i class="fal fa-shopping-cart"></i>
               <span class="badge cart-items-count">{{request.session.cart_data_obj|length}}</span>
              </a>
            </div>
          </div>
          <div class="col-auto d-block d-lg-none">
            <button type="button" class="vs-menu-toggle">
              <i class="far fa-bars"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </header>
  
  
  
            

templates/store/ffless/welcome.html
  
    {% extends "partials/ffless/basemain.html" %}
    {% load static %}
    
    {% block title %}
       Yummy tummy Goodies 
    {% endblock title %}
        
    {% block content %}
    {% load humanize %}

    
<section  class="" data-bg-src="{% static 'assets/img/shape/shpe-8-1.png' %}"  style="background-image: url({% static 'assets/img/shape/shpe-8-1.png' %});'">
<div class="container"  >


    <div class="section-title text-center" style="padding-top: 70px;">
      <!-- <div class="sec-icon">
        <img src="{% static 'assets/img/foodforless.png'%}" style="width: 100%;" alt="icon">

      </div> -->
      <h4 class="sec-title5">Hey {{user.username}}, <br> welcome to Yummy tummy Goodies </h4>
    </div>
    {% if messages %} {% for message in messages %}
    <div
      class="alert alert-{{message.tags}} text-center"
      style="margin-top: 10px"
    >
      <h4><strong>{{message}}</strong></h4>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    <script>
      setTimeout(() => {
        $(".alert").alert("close");
      }, 30);
    </script>
    {% endfor %} {% endif %}
    <div class="container">
      <div style="margin: 0px;">
      <div class="row gx-0">
        <div class="col-md-4 feature-style2">
          <div class="feature-img">
            <img src="{% static 'assets/img/icons/feature-icon-2-2.png'%}" alt="icons">
          </div>
          <h3 class="feature-title">Shop Our Stores</h3>
          <p class="feature-text">Choose a veg box and top up from our range of organic veg, fruit, meat, dairy and recipe boxes.</p>
        </div>
        
        <div class="col-md-4 feature-style2">
          <div class="feature-img">
            <img src="{% static 'assets/img/icons/feature-icon-2-3.png'%}" alt="icons">

          </div>
          <h3 class="feature-title">Amazing beg, Good Health</h3>
          <p class="feature-text">Your local veg team will deliver for free - and collect your packaging to reuse. No need to be home!</p>
        </div>
        <div class="col-md-4 feature-style2">
          <div class="feature-img">
            <img src="{% static 'assets/img/icons/feature-icon-2-1.png'%}" alt="icons">

          </div>
          <h3 class="feature-title">Enjoy free delivery</h3>
          <p class="feature-text">Live life on the veg, cook and eat brilliant seasonal dishes, and make a positive impact on the world.</p>
        </div>
      </div>

      <div class="text-center">
        <a href="{% url 'store:shop' %}" class="vs-btn style3 ls-btn">Start shopping<i class="far fa-angle-right"></i>

      </div>
    </div>
  </div>
  </div>
  </section>
  {% endblock %}