blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<slug>/', views.category_detail, name="category_detail"),
    path('<pid>', views.blogDetail, name="blog-detail"),

]

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("my-dashboard/", views.buyer_account, name="buyer-dashboard"),
    path("profile/", views.buyer_profile, name="profile"),
    path("settings/", views.buyer_profile_settings, name="settings"),
    path("my-orders/", views.buyer_orders, name="buyer-orders"),
    path("my-orders/<oid>/", views.buyer_order_detail, name="buyer-order-detail"),

    # Shipping Address
    path("my-address/", views.buyer_address, name="buyer-address"),
    path("welcome-address/", views.buyer_welcome_address, name="buyer_welcome_address"),
    path("my-address/edit/<id>/", views.buyer_edit_address, name="buyer-edit-address"),
    path("my-address/delete/<id>/", views.buyer_delete_address, name="buyer-delete-address"),

    # Billing Address
    path("my-billing-address/", views.buyer_billing_address, name="buyer-billing-address"),
    path("my-billing-address/edit/<id>/", views.buyer_edit_billing_address, name="buyer-edit-billing-address"),
    path("add_billing_address", views.add_billing_address, name="add_billing_address"),
    path("my-billing-address/delete/<id>/", views.buyer_delete_billing_address, name="buyer_delete_billing_address"),

    path("my-wishlist/", views.buyer_wishlist, name="buyer-wishlist"),
    path("my-invoices/", views.buyer_invoices, name="buyer-invoices"),
    path("my-invoice/<oid>/", views.buyer_invoice_detail, name="buyer-invoice-detail"),
    path("my-bids/", views.buyer_bids, name="buyer_bids"),
    path("my-bids-detail/<pid>/<bid>", views.buyer_bids_detail, name="buyer_bids_detail"),
    path("order-tracker/", views.buyer_track_order, name="order-tracker"),
    path("tracked-order/<oid>/", views.tracked_order, name="tracked-order"),
    path("buyer_offer", views.buyer_offer, name="buyer_offer"),
    path("buyer_offer_detail/<pid>/<oid>/", views.buyer_offer_detail, name="buyer_offer_detail"),
    path("cancel_order/<oid>/", views.cancel_order, name="cancel_order"),
    path("cancel_orderitem/", views.cancel_orderitem, name="cancel_orderitem"),

    # Messaging
    path('inbox/', views.inbox, name="buyer_message"),
    path('inbox/<username>/', views.get_inbox, name="inbox-detail"),
    path('send_message_ajax/<username>/', views.send_message_ajax, name="send_message_ajax"),
    path('search_user/', views.search_users, name="search_users"),

    # Ajax
    path("delete-wishlist/<id>/", views.delete_from_wishlist, name="delete-wishlist"),
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),
    path("make-default-address/", views.make_address_default, name="make-default-address"),
    path("make-billing-default-address/", views.make_billing_address_default, name="make-default-billing-address"),

]

ecommerce_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('user/', include("userauths.urls")),
    path('b/', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('base/', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from store import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="home"),
    path("homemain/", views.indexmain, name="homemain"),
    path("welcome/", views.welcome, name="welcome"),
    path("offer/", views.offer, name="offer"),
    path("category/", views.category_list, name="category"),
    path("shop/", views.shop, name="shop"),
    path("hot_deals/", views.hot_deals, name="hot_deals"),
    path("search/", views.search_list, name="search"),
    path("detail/<slug:slug>/", views.product_detail, name="product-detail"),
    path("my-cart/", views.cart_view, name="cart-view"),
    path("category/<cid>/", views.category_detail, name="category_detail"),
    path("shipping_address/", views.shipping_address, name="shipping_address"),
    path("checkout/<oid>/", views.checkout_view, name="checkout"),
    path("custom-checkout/<oid>/", views.custom_checkout_view, name="checkout2"),
    path('checkout/order-detail/<id>/', views.PaymentConfirmation.as_view(), name='order-detail'),
    path('success-payment/', views.PaymentSuccessView, name='success'),
    path('failed-payment/', views.PaymentFailedView, name='failed'),
    
    # Bidding and Auctioon
    path("auction/", views.auction, name="auction"),
    path("auction_detail/<pid>/", views.auction_detail, name="auction_detail"),
    path("auction_update/<pid>/<bid>/", views.auction_update, name="auction_update"),
    
    # Paypal
    path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-completed/<oid>/", views.payment_completed_view, name="payment-completed"),
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

    # Ajax URLs
    path("ajax/add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("ajax/helpful-review/", views.helpful_review, name="helpful-review"),
    path("ajax/add-review/<int:pid>/", views.add_review, name="add-review"),
    path("ajax/ask-question/", views.ask_question, name="ask-question"),
    path('ajax/update-cart/',views.update_cart,name='update-cart'),
    path('ajax/delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),

    # API URLs
    path('api/checkout-session/<id>/', views.create_checkout_session, name='api_checkout_session'),
    path('country_get/', views.country_get, name='country_get'),


]

userauths/urls.py
from django.urls import path
from userauths import views
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500


app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.Register, name="sign-up"),
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    path("sign-in-2/", views.loginView, name="sign-in-2"),
    path("sign-out/", views.logoutView, name="sign-out"),
    path("vendor_sign_in/", views.loginAsVendor, name="vendor_sign_in"),
    path("check_email/", views.check_email, name="check_email"),
    
    
]

templates/buyer/address-edit.html
{% extends "partials/ffless/basestandard.html" %}
 {% load static %} 
{% block title %}
  Edit Address
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
<!-- {% crispy form %} -->
<section class="oufr-log-rfeg bgcf-f5">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-xl-12 col-xxl-12 m-auto">
        <div class="log_reg_form mt70-992">
          <h2 class="title">Update Address</h2>
          <div class="login_form">
            <form method="POST">
              {% csrf_token %}
              <div class="mb-2 mr-sm-2">{{form.as_p}}</div>

              <button type="submit" class="btn purple-btn btn-thm">Save Update</button>
              <a href="{% url 'core:buyer-address' %}" class="btn btn-secondary">Go Back</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/buyer/buyer-cancel-order.html
{% extends "partials/ffless/basestandard.html" %}
 {% load static %} 
{% block title %}
  Cancel Order
{% endblock title %}
{% load crispy_forms_tags %} {% block content %}
<section class="our-dashbord dashbord" style="margin-top: 0">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-xl-12">
        <div class="row">
          <div class="col-xl-12" style="margin-top: -100px;">
            <div class="account_user_deails pl40 pl0-md">
              <div class="ui_kit_tab style2">
                <div class="tab-content pt20 row" id="myTabContent">
                  <div
                    class="tab-pane fade show active col-lg-12"
                          id="t20"
                                role="tabpanel"
aria-labelledby="t20-tab"
                  >
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30 text-danger">
                        Cancel Order #{{ order.oid }}
                      </h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">Product</th>
                              <th scope="col">Date</th>
                              <th scope="col">Payment</th>
                              <th scope="col">Delivery Status</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in orderitems %}
                            <tr>
                              <th scope="row">
                                <a
                                  href="{% url 'store:product-detail' o.product_obj.pid %}"
                                  class="dashed-custom"
                                  >{{o.product_obj.title|truncatechars:27}}</a
                                >
                              </th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{o.date}}</small></td>

                              {% if o.paid == True %}
                              <td class="text-success">Paid</td>
                              {% else %}
                              <td class="text-success">Not Paid</td>
                              {% endif %}

                              <td class="status">
                                <span class="stylde4"
                                  >{{o.delivery_status|title}}</span
                                >
                              </td>
                              <td>{{ cs }}{{ o.total }}</td>

                              {% if o.cancelled == True %}
                              <td class="status">
                                <a class="btn btn-success disabled"
                                  >Order Cancelled</a
                                >
                              </td>
                              {% else %}
                              <td class="status">
                                <a
                                  data-order-item="{{o.id}}"
                                  id="cancel-order"
                                  class="btn btn-danger orderitem{{o.id}}"
                                  >Cancel</a
                                >
                              </td>
                              {% endif %}
                            </tr>
                            {% empty %}
                            <tr>
                              <td><h4>No Orders Yet</h4></td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div
                    class="tab-pane fade col-lg-12"
                    id="baby"
                    role="tabpanel"
                    aria-labelledby="baby-tab"
                  >
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Shipped</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Product</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Payment</th>
                              <th scope="col">Delivery Status</th>
                              <th scope="col">Order Status</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in shipped %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">
                                {{o.payment_status|title}}
                              </td>
                              <td class="status">
                                <span class="stylde4"
                                  >{{o.delivery_status|title}}</span
                                >
                              </td>
                              <td class="status">
                                <span class="stdyle4"
                                  >{{o.order_status|title}}</span
                                >
                              </td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status">
                                <span class="style4"
                                  ><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}"
                                    >View Detail</a
                                  ></span
                                >
                              </td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td><h4>No Orders Yet</h4></td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div
                    class="tab-pane fade col-xl-12"
                    id="furniture"
                    role="tabpanel"
                    aria-labelledby="furniture-tab"
                  >
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Delivered Orders</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Product</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Payment</th>
                              <th scope="col">Delivery Status</th>
                              <th scope="col">Order Status</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in collected %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">
                                {{o.payment_status|title}}
                              </td>
                              <td class="status">
                                <span class="stylde4"
                                  >{{o.delivery_status|title}}</span
                                >
                              </td>
                              <td class="status">
                                <span class="stdyle4"
                                  >{{o.order_status|title}}</span
                                >
                              </td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status">
                                <span class="style4"
                                  ><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}"
                                    >View Detail</a
                                  ></span
                                >
                              </td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td><h4>No Orders Yet</h4></td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- nav tab contents End -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/buyer/invoices.html
{% extends "partials/ffless/basestandard.html" %}
{% load static %}
{% block title %}
  Invoices
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<section class="our-dashbord dashbord">
  <div class="container">
    <div class="row">
      {% include 'buyer/nav-desktop.html' %}
      <div class="col-lg-9 col-xl-9">
        {% include 'buyer/nav-mobile.html' %}
        <div class="row">
          <div class="col-xl-12"style="margin-top: -100px;">
            <div class="account_user_deails pl40 pl0-md">
              <h2 class="title mb30">My Invoices</h2>
              <div class="ui_kit_tab style2">
                <!-- nav tab Nav List Start -->
                <div class="tab-content pt20 row" id="myTabContent">
                  <div class="tab-pane fade show active col-lg-12" id="t20" role="tabpanel" aria-labelledby="t20-tab">
                    <div class="account_user_deails pl40 pl0-lg">
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light" id="">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Product</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Payment</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for i in invoices %}
                            <tr>
                              <th scope="row">{{i.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{i.date}}</small></td>
                              <td class="text-success">{{i.payment_status|title}}</td>
                              <td>{{ cs }}{{ i.total }}</td>
                              <td class="statufs"><span class="style4"><a
                                    href="{% url 'core:buyer-invoice-detail' i.oid %}"><i class="fas fa-eye">
                                    </i></a></span></td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td>
                                <h4>No Orders Yet</h4>
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade col-lg-12" id="baby" role="tabpanel" aria-labelledby="baby-tab">
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Shipped</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Product</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Payment</th>
                              <th scope="col">Delivery Status</th>
                              <th scope="col">Order Status</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in shipped %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">{{o.payment_status|title}}</td>
                              <td class="status"><span class="stylde4">{{o.delivery_status|title}}</span></td>
                              <td class="status"><span class="stdyle4">{{o.order_status|title}}</span></td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status"><span class="style4"><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}">View Detail</a></span></td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td>
                                <h4>No Orders Yet</h4>
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div class="tab-pane fade col-xl-12" id="furniture" role="tabpanel" aria-labelledby="furniture-tab">
                    <div class="account_user_deails pl40 pl0-lg">
                      <h2 class="title mb30">Delivered Orders</h2>
                      <div class="order_table table-responsive">
                        <table class="table">
                          <thead class="table-light">
                            <tr>
                              <th scope="col">ID</th>
                              <!-- <th scope="col">Product</th> -->
                              <th scope="col">Date</th>
                              <th scope="col">Payment</th>
                              <th scope="col">Delivery Status</th>
                              <th scope="col">Order Status</th>
                              <th scope="col">Total</th>
                              <th scope="col">Action</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for o in collected %}
                            <tr>
                              <th scope="row">{{o.oid}}</th>
                              <!-- <td>{{o.product}}</td> -->
                              <td><small>{{o.date}}</small></td>
                              <td class="text-success">{{o.payment_status|title}}</td>
                              <td class="status"><span class="stylde4">{{o.delivery_status|title}}</span></td>
                              <td class="status"><span class="stdyle4">{{o.order_status|title}}</span></td>
                              <td>{{ cs }}{{ o.total }}</td>
                              <td class="status"><span class="style4"><a
                                    href="{% url 'core:buyer-order-detail' o.oid %}">View Detail</a></span></td>
                            </tr>
                            {% empty %}
                            <tr>
                              <td>
                                <h4>No Orders Yet</h4>
                              </td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>

                  </div>
                </div>
                <!-- nav tab contents End -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/buyer/nav-mobile.html
<style>
   ul,li{
      list-style: none;
   }
</style>
<div class="row" style="margin-top: 90px;">
   <!-- style="margin-top: 100px;" -->
    <div class="col-lg-12">
      
       <div class="dashboard_navigationbar dn db-md " style="margin-top: -100px;">
         <div class="account_details_user d-flex pb10 bb1 mb10 shadow p-3" style="border-radius: 10px;">
            <img class="me-3" src="{{request.user.profile.image.url}}" style="width: 50px; height: 50px; border-radius: 50%; object-fit: cover;" alt="Generic placeholder image">
            <div class="content_details text-start">
               
               {% if request.user.profile.full_name %}
               <h5 class="title">{{request.user.profile.full_name|title}}</h5>
               {% else %}
               <h5 class="title">{{request.user.username|title}}</h5>
               {% endif %}
                  
               <!-- <a class="stitle" >{{request.user.email}}</a> <br> -->
               <a class="stitle" >Account ID: <b><i>{{request.user.id}}</i></b></a>

            </div>
         </div>
          <div class="dropdown">
             <button onclick="myFunction()" class="dropbtn"><i class="fas fa-bars pr10"></i> Dashboard Navigation</button>
             <ul id="myDropdown" class="dropdown-content">
                <li><a class="active" href="{% url 'core:buyer-dashboard' %}"><span class="bi bi-grid-3x3-gap-fill"></span>Dashboard</a></li>
                <li><a class="active" href="{% url 'core:profile' %}"><span class="fas fa-user"></span>Account Details</a></li>
                <li><a href="{% url 'core:buyer-orders' %}"><span class="fas fa-list"></span>Order</a></li>
                <li><a href="{% url 'core:buyer_bids' %}"><span class="fas fa-chart-simple"></span>My Bids</a></li>
                <li><a href="{% url 'core:buyer_offer' %}"><span class="bi bi-shop"></span>My Offers</a></li>
                <li><a href="{% url 'core:buyer_message' %}"><span class="bi bi-chat-right-dots-fill"></span>Message</a></li>
                <li><a href="{% url 'core:buyer-address' %}"><span class="fas fa-location"></span>Address</a></li>
                <li><a href="{% url 'core:buyer-wishlist' %}"><span class="fas fa-heart"></span>Wishlist</a></li>
                <li><a href="{% url 'core:buyer-invoices' %}"><span class="fas fa-file-invoice"></span>Invoices</a></li>
                <li><a href="{% url 'core:settings' %}"><span class="bi bi-gear-fill"></span>Settings</a></li>
                <li><a href="{% url 'userauths:sign-out' %}"><span class="fas fa-right-from-bracket"></span>Logout</a></li>
             </ul>
          </div>
          
       </div>
    </div>
 </div>