blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blogList, name="blog-list"),
    path('category/<slug>/', views.category_detail, name="category_detail"),
    path('<pid>', views.blogDetail, name="blog-detail"),

]

core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("my-dashboard/", views.buyer_account, name="buyer-dashboard"),
    path("profile/", views.buyer_profile, name="profile"),
    path("settings/", views.buyer_profile_settings, name="settings"),
    path("my-orders/", views.buyer_orders, name="buyer-orders"),
    path("my-orders/<oid>/", views.buyer_order_detail, name="buyer-order-detail"),

    # Shipping Address
    path("my-address/", views.buyer_address, name="buyer-address"),
    path("welcome-address/", views.buyer_welcome_address, name="buyer_welcome_address"),
    path("my-address/edit/<id>/", views.buyer_edit_address, name="buyer-edit-address"),
    path("my-address/delete/<id>/", views.buyer_delete_address, name="buyer-delete-address"),

    # Billing Address
    path("my-billing-address/", views.buyer_billing_address, name="buyer-billing-address"),
    path("my-billing-address/edit/<id>/", views.buyer_edit_billing_address, name="buyer-edit-billing-address"),
    path("add_billing_address", views.add_billing_address, name="add_billing_address"),
    path("my-billing-address/delete/<id>/", views.buyer_delete_billing_address, name="buyer_delete_billing_address"),

    path("my-wishlist/", views.buyer_wishlist, name="buyer-wishlist"),
    path("my-invoices/", views.buyer_invoices, name="buyer-invoices"),
    path("my-invoice/<oid>/", views.buyer_invoice_detail, name="buyer-invoice-detail"),
    path("my-bids/", views.buyer_bids, name="buyer_bids"),
    path("my-bids-detail/<pid>/<bid>", views.buyer_bids_detail, name="buyer_bids_detail"),
    path("order-tracker/", views.buyer_track_order, name="order-tracker"),
    path("tracked-order/<oid>/", views.tracked_order, name="tracked-order"),
    path("buyer_offer", views.buyer_offer, name="buyer_offer"),
    path("buyer_offer_detail/<pid>/<oid>/", views.buyer_offer_detail, name="buyer_offer_detail"),
    path("cancel_order/<oid>/", views.cancel_order, name="cancel_order"),
    path("cancel_orderitem/", views.cancel_orderitem, name="cancel_orderitem"),

    # Messaging
    path('inbox/', views.inbox, name="buyer_message"),
    path('inbox/<username>/', views.get_inbox, name="inbox-detail"),
    path('send_message_ajax/<username>/', views.send_message_ajax, name="send_message_ajax"),
    path('search_user/', views.search_users, name="search_users"),

    # Ajax
    path("delete-wishlist/<id>/", views.delete_from_wishlist, name="delete-wishlist"),
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),
    path("make-default-address/", views.make_address_default, name="make-default-address"),
    path("make-billing-default-address/", views.make_billing_address_default, name="make-default-billing-address"),

]

ecommerce_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('user/', include("userauths.urls")),
    path('b/', include("core.urls")),
    path('vendor/', include("vendor.urls")),
    path('base/', include("addons.urls")),
    path('report/', include("reports.urls")),
    path('blog/', include("blog.urls")),
    path('help-center/', include("help_center.urls")),

    
    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Change Password
    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    
    
    # Re-Captcha Validation
    # path('captcha/', include('captcha.urls')),
    
    # Password Reset
    path('user/password-reset/', auth_views.PasswordResetView.as_view( template_name='userauths/password-reset/password_reset.html', subject_template_name='userauths/password-reset/password_reset_subject.txt', email_template_name='userauths/password-reset/password_reset_email.html', success_url='/user/check_email/' ), name='password_reset'),
    path('user/password-reset/done/', auth_views.PasswordResetDoneView.as_view( template_name='userauths/password-reset/password_reset_done.html' ), name='password_reset_done'),
    path('user/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( template_name='userauths/password-reset/password_reset_confirm.html' ), name='password_reset_confirm'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from store import views

app_name = "store"

urlpatterns = [
    path("", views.index, name="home"),
    path("homemain/", views.indexmain, name="homemain"),
    path("welcome/", views.welcome, name="welcome"),
    path("offer/", views.offer, name="offer"),
    path("category/", views.category_list, name="category"),
    path("shop/", views.shop, name="shop"),
    path("hot_deals/", views.hot_deals, name="hot_deals"),
    path("search/", views.search_list, name="search"),
    path("detail/<slug:slug>/", views.product_detail, name="product-detail"),
    path("my-cart/", views.cart_view, name="cart-view"),
    path("category/<cid>/", views.category_detail, name="category_detail"),
    path("shipping_address/", views.shipping_address, name="shipping_address"),
    path("checkout/<oid>/", views.checkout_view, name="checkout"),
    path("custom-checkout/<oid>/", views.custom_checkout_view, name="checkout2"),
    path('checkout/order-detail/<id>/', views.PaymentConfirmation.as_view(), name='order-detail'),
    path('success-payment/', views.PaymentSuccessView, name='success'),
    path('failed-payment/', views.PaymentFailedView, name='failed'),
    
    # Bidding and Auctioon
    path("auction/", views.auction, name="auction"),
    path("auction_detail/<pid>/", views.auction_detail, name="auction_detail"),
    path("auction_update/<pid>/<bid>/", views.auction_update, name="auction_update"),
    
    # Paypal
    path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-completed/<oid>/", views.payment_completed_view, name="payment-completed"),
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

    # Ajax URLs
    path("ajax/add-to-cart/", views.add_to_cart, name="add-to-cart"),
    path("ajax/helpful-review/", views.helpful_review, name="helpful-review"),
    path("ajax/add-review/<int:pid>/", views.add_review, name="add-review"),
    path("ajax/ask-question/", views.ask_question, name="ask-question"),
    path('ajax/update-cart/',views.update_cart,name='update-cart'),
    path('ajax/delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),

    # API URLs
    path('api/checkout-session/<id>/', views.create_checkout_session, name='api_checkout_session'),
    path('country_get/', views.country_get, name='country_get'),


]

store/views.py
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseNotFound, JsonResponse
from django.db import models
from django.shortcuts import redirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.conf import settings
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.db.models import Q, Count, Sum, F, FloatField
from django.core.mail import EmailMultiAlternatives, send_mail
from django.template.loader import render_to_string
from django.shortcuts import render, HttpResponse
from django.contrib.gis.geoip2 import GeoIP2
from django.core.paginator import Paginator


from store.forms import CheckoutForm, ReviewForm
from store.models import Product, Category, CartOrder, CartOrderItem, Brand, Gallery, Review, ProductFaq, ProductBidders, ProductOffers
from core.models import Address
from blog.models import Post
from vendor.forms import CouponApplyForm
from vendor.models import Vendor, OrderTracker, PayoutTracker, Notification, Coupon
from addons.models import BasicAddon, Company, TaxRate

from datetime import datetime as d
from datetime import datetime
import datetime
import pytz
import json
import stripe
import requests
from decimal import Decimal
from anymail.message import attach_inline_image_file
from paypal.standard.forms import PayPalPaymentsForm


utc=pytz.UTC

def index(request):
    addon = BasicAddon.objects.filter().first()
    brands = Brand.objects.filter(active=True)
    products = Product.objects.filter(status="published", featured=True).order_by("-id")[:10]
    top_selling_products = Product.objects.filter(status="published").order_by("-orders")[:10]
    hot_deal = Product.objects.filter(status="published", hot_deal=True).first()
    all_products = Product.objects.filter(status="published")[:16]
    posts = Post.objects.filter(status="published", featured=True)
    
    query = request.GET.get("q")
    if query:
        products = products.filter(Q(title__icontains=query)|Q(description__icontains=query)).distinct()
        
    
    
    context = {
        "all_products":all_products,
        "addon":addon,
        "posts":posts,
        "brands":brands,
        'hot_deal':hot_deal,
        "products":products,
        "top_selling_products":top_selling_products,
    }
    return render(request, 'store/yummytummy/indexmain.html', context)
      


def indexmain(request):
    addon = BasicAddon.objects.filter().first()
    brands = Brand.objects.filter(active=True)
    products = Product.objects.filter(status="published", featured=True).order_by("-id")[:10]
    top_selling_products = Product.objects.filter(status="published").order_by("-orders")[:10]
    hot_deal = Product.objects.filter(status="published", hot_deal=True).first()
    all_products = Product.objects.filter(status="published")[:16]
    posts = Post.objects.filter(status="published", featured=True)
    
    query = request.GET.get("q")
    if query:
        products = products.filter(Q(title__icontains=query)|Q(description__icontains=query)).distinct()
        
    
    
   
    return render(request, 'store/yummytummy/indexmain.html',  context={
        'all_products':all_products,
        'addon':addon,
        'posts':posts,
        'brands':brands,
        'hot_deal':hot_deal,
        'products':products,
        'top_selling_products':top_selling_products,
        'local_css_urls': [ " assets/css/style.css",
                            " assets/css/bootstrap.min.css",
                            " assets/css/fontawesome.min.css",
                            " assets/css/app.min.css"],
        'local_js_urls':  [
                        "assets/js/main.js",
                        "assets/js/ajax-mail.js",
                        "assets/js/app.min.js",
                        "assets/js/vscustom-carousel.min.js",
                        "assets/js/vsmenu.min.js",
                        "assets/js/jquery-3.6.0.min.js"
                        ]
    })

def welcome(request):
    return render(request, 'store/ffless/welcome.html')

def category_list(request):
    categories_ = Category.objects.filter(active=True)
    
    context = {
        "categories_":categories_,
    }
    return render(request, "store/categories.html", context)



def search_list(request):
    products = Product.objects.filter(status="published").order_by("-id")
    product_count = Product.objects.filter(status="published").order_by("-id")
    
    query = request.GET.get("q")
    if query:
        products = products.filter(Q(title__icontains=query)|Q(description__icontains=query)|Q(category__title__icontains=query)).distinct()
        product_count = product_count.filter(Q(title__icontains=query)|Q(description__icontains=query)|Q(category__title__icontains=query)).distinct()
        
    paginator = Paginator(products, 16)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    
    
    context = {
        "product_count":product_count,
        "products":products,
        "query":query,
    }
    return render(request, "store/search_list.html", context)


def shop(request):
    brands = Brand.objects.filter(active=True)
    products = Product.objects.filter(status="published").order_by("-id")
    products_couunt = Product.objects.filter(status="published").order_by("-id")
    top_selling = Product.objects.filter(status="published").order_by("-orders")[:20]
    
    paginator = Paginator(products, 16)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    
    context = {
        "products_couunt":products_couunt,
        "brands":brands,
        "products":products,
        "top_selling":top_selling,
    }
    return render(request, "store/shop.html", context)


def hot_deals(request):
    products = Product.objects.filter(status="published", hot_deal=True).order_by("-id")
    
    query = request.GET.get("q")
    if query:
        products = products.filter(Q(title__icontains=query)|Q(description__icontains=query)).distinct()
    
    paginator = Paginator(products, 16)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    
    context = {
        "products":products,
    }
    return render(request, "store/hot-deals.html", context)



def category_detail(request, cid):
    category__ = Category.objects.get(cid=cid)
    top_selling = Product.objects.filter(status="published", category=category__).order_by("-id")[:10]
    products = Product.objects.filter(status="published", category=category__).order_by("orders")
    
    
    context = {
        "category__":category__,
        "products":products,
        "top_selling":top_selling,
    }
    return render(request, "store/category-detail.html", context)

def auction(request):
    products = Product.objects.filter(status="published", type="auction").order_by("-id")
    products_count = Product.objects.filter(status="published", type="auction")
    
    query = request.GET.get("q")
    if query:
        products = products.filter(Q(title__icontains=query)|Q(description__icontains=query)).distinct()
    
    paginator = Paginator(products, 12)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)

    context = {
        "products":products,
        "products_count":products_count,
    }
    return render(request, "store/auction.html", context)

@login_required
def auction_detail(request, pid):
    product = Product.objects.get(status="published", type="auction", pid=pid)
    bidders = ProductBidders.objects.filter(product=product, active=True).order_by("-price")[:3]
    other_bidders = ProductBidders.objects.filter(product=product, active=True).order_by("-price")
    message = ""
    alert_tag = "success"
    completed = False
    winner = ProductBidders.objects.filter(product=product, active=True).order_by("-price").first()
    
    
    if timezone.now() < product.ending_date:
        message = "Bidding is still on going."
        completed = False
        product.auction_status = "on_going"
        product.bidding_ended = False
        product.save()
        try:
            winner.winner = False
            winner.win_status = "pending"
            winner.save()
        except:
            pass
        ProductBidders.objects.filter(product=product).update(winner=False)
        
    else:
        message = "Bidding have been completed"
        product.auction_status = "finished"
        product.bidding_ended = True
        product.save()
        completed = True
        try:
            winner.winner = True
            winner.win_status = "won"
            winner.save()
        except:
            pass
    
    if request.method == "POST":
        price = request.POST.get("price")
        if Decimal(price) < product.price:
            messages.warning(request, "You bidding price cannot be lower than the starting price")
            return redirect("store:auction_detail", product.pid)
        
        ProductBidders.objects.create(
            user=request.user,
            product=product,
            price=price,
            email=request.user.email,
            active=True
        )
        product.bidders.add(request.user)
        product.save()
        messages.success(request, "Bidding Placed Successfully.")
        return redirect("store:auction_detail", product.pid)
    
    context = {
        "winner":winner,
        "completed":completed,
        "alert_tag":alert_tag,
        "message":message,
        "product":product,
        "bidders":bidders,
        "other_bidders":other_bidders,
    }
    return render(request, "store/auction_detail.html", context)

@login_required
def auction_update(request, pid, bid):

templates/store/auction.html
{% extends "partials/ffless/basestandard.html" %}
{% load static %}
{% block content %}

<!-- Listing Grid View -->
<section class="our-listing pt0">
  <div class="container">
    <div class="row mt60">
      <div class="col-lg-3 col-xl-2 d-none d-lg-block">
        <div class="sidebar_accordion_widget">
          <div class="faq_according text-start">
            <div class="accordion" id="accordionExample">
              <!-- Add Filter cards here -->


              <!-- end Filter cards here -->
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-12 col-xl-12 pl50 pl15-md">
        <div class="row">
          <div class="col-lg-12">
            <div class="main-title bb1 pb10">
              <h2 class="title">Auctioned Products</h2>
              <p>Bid against other users on any desired product.</p>
            </div>
          </div>
        </div>
        <div class="row">

          <div class="row">
            {% for p in products %}
            <div class="col-6 col-lg-4 col-xl-3 p-1">
              {% include 'store/product_list.html' %}

            </div>
            {% empty %}
            <h4>No Auctioned Product Yet</h4>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/store/cart.html
{% extends "partials/ffless/basestandard.html" %}
 {% load static %}
 {% block title %}
Cart 
 {% endblock title %}
 {% block content %}
{% load crispy_forms_tags %}
<style>
  ul,
  li {
    list-style: none;
  }
  @media screen and (max-width: 1100px) {
    table {
      border: 0;
    }

    table caption {
      font-size: 1.3em;
    }

    table thead {
      display: none;
    }

    table tr {
      border-bottom: 3px solid #ddd;
      display: block;
      margin-bottom: 0.625em;
    }

    table td,
    th {
      border-bottom: 1px solid #ddd;
      display: block;
      font-size: 0.8em;
      text-align: right;
    }

    table td::before {
      content: attr(data-label);
      float: left;
      font-weight: bold;
      text-transform: uppercase;
    }

    table td:last-child {
      border-bottom: 0;
    }
  }
</style>
<div class="body_content_wrapper position-relative" id="cartList">
  <!-- Inner Page Breadcrumb -->
  <section class="inner_page_breadcrumb" style="margin-top: 10px">
    <div class="container">
      <div class="row">
        <div class="col-xl-6">
          <div class="breadcrumb_content">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'store:home' %}">Home</a>
              </li>
              <li class="breadcrumb-item"><a>Shop</a></li>
              <li class="breadcrumb-item active" aria-current="page">
                <a>Shopping Cart</a>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Shop Checkouts Content -->
  <section class="shop-cart pt30">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-lg-4 m-auto">
          <div class="main-title text-center mb50">
            <h2 class="title">Shopping Cart</h2>
            <!-- <input type="text" name="" id=""> -->
          </div>
        </div>
      </div>
      <div class="row mt15" id="cartList">
        <p class="para">
          You have <span class="cart-list">{{totalcartitems }}</span> items in
          your cart
        </p>

        <div class="col-lg-8 col-xl-9">
          <div class="shopping_cart_table table-responsive">
            <table class="table table-borderless">
              <thead>
                <tr>
                  <th scope="col">PRODUCT</th>
                  <th scope="col">PRICE</th>
                  <th scope="col">QUANTITY</th>
                  <th scope="col">TOTAL</th>
                  <th scope="col">UPDATE</th>
                  <th scope="col">REMOVE</th>
                </tr>
              </thead>
              <tbody class="table_body">
                {% for product_id, p in cart_data.items %}
                <tr>
                  <th scope="row">
                    <ul class="cart_list d-block d-xl-flex">
                      <li class="ps-1 ps-sm-4 pe-1 pe-sm-4">
                        <a href="#"
                          ><img
                            src="{{p.image}}"
                            style="
                              width: 100px;
                              height: 80px;
                              object-fit: cover;
                              border-radius: 10px;
                            "
                            alt="cart1.png"
                        /></a>
                      </li>
                      <li class="ms-2 ms-md-3">
                        <a
                          class="cart_title"
                          href="{% url 'store:product-detail' p.product_slug %}"
                        >
                          <span class="fz16">{{p.title|truncatechars:27}}</span>
                          <br />
                          <span class="fz16">By: <b><i>{{p.shop_name|title}}</i></b></span>
                          <br />
                          <span class="fz16">Stock Qty: </a><span id="stock_qty{{product_id}}">{{p.product_stock_qty}}</span></span>

                          <br />
                        </a>
                      </li>
                    </ul>
                  </th>
                  <td>{{ cs }}{{p.price}}</td>
                  <input
                    type="hidden"
                    class="product-shipping_amount-{{ product_id }}"
                    value="{{ p.shipping_amount }}"
                  />
                  <input
                    type="hidden"
                    class="product-product_processing_fee-{{ product_id }}"
                    value="{{ p.product_processing_fee }}"
                  />
                  <input
                    type="hidden"
                    class="product-product_tax_fee-{{ product_id }}"
                    value="{{ p.product_tax_fee }}"
                  />

                  <input type="hidden" class="product-product_stock_qty-{{ product_id }}" value="{{ p.product_stock_qty }}" />


                  <td>
                    <div class="cart_btn">
                      <div class="quantity-block">
                        <button
                          class="quantity-arrow-minus inner_page"
                          id="decrease-btn"
                          data-btn="{{product_id}}"
                          data-cart-index="{{ product_id }}"
                        >
                          <span class="fa fa-minus"></span>
                        </button>
                        <input
                          class="quantity-num-{{ product_id }} quantity-num inner_page product-qty-{{ product_id }}"
                          id="qty{{product_id}}"
                          type="number"
                          value="{{p.qty}}"
                        />
                        <button
                          class="quantity-arrow-plus inner_page"
                          id="increase-btn"
                          data-btn="{{product_id}}"
                          data-cart-index="{{ product_id }}"
                        >
                          <span class="fas fa-plus"></span>
                        </button>
                      </div>
                    </div>
                    <!-- <input class="cart_count text-center" placeholder="2" type="number"> -->
                  </td>
                  <td class="">{{ cs }}{% widthratio p.price 1 p.qty %}</td>
                  <td class="action text-center" data-title="Remove">
                    <button
                      style="border: none; background: none"
                      class="text-body update-item"
                      data-item="{{ product_id }}"
                    >
                      <i class="bi bi-arrow-clockwise"></i>
                    </button>
                  </td>
                  <td class="action text-center" data-title="Remove">
                    <button
                      style="border: none; background: none"
                      class="text-body delete-item"
                      data-item="{{ product_id }}"
                    >
                      <i class="bi bi-trash"></i>
                    </button>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td>
                    Your cart is empty,
                    <a href="{% url 'store:shop' %}">continue shopping</a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="col-lg-4 col-xl-3">
          <div class="order_sidebar_widget style2">
            <h4 class="title">Cart Totals</h4>
            <ul>
              <li class="subtitle">
                <p>
                  Product Subtotal
                  <span class="float-end"
                    >{{ cs }}{{cart_total_amount|floatformat:2}}</span
                  >
                </p>
              </li>
              <!-- <li class="subtitle"><p>Order Discounts <span class="float-end">-$30.01</span></p></li> -->
              <li class="subtitle">
                <p>
                  Estimated Shipping
                  <i
                    data-bs-toggle="tooltip"
                    data-bs-placement="top"
                    title="Tooltip on top"
                    class="bi bi-info-circle-fill"
                  ></i>
                  <span class="float-end"
                    >{{ cs }}{{total_shipping_amount|floatformat:2}}</span
                  >
                </p>
              </li>
              <li class="subtitle">
                <p>
                  Estimated {{tax_country.custom_name}}
                  <i
                    data-bs-toggle="tooltip"
                    data-bs-placement="top"
                    title="Tooltip on top"
                    class="bi bi-info-circle-fill"
                  ></i
                  ><span class="float-end"
                    >{{cs}}{{ tax_amount_|floatformat:2 }}</span
                  >
                </p>
              </li>
              <li class="subtitle">
                <p>
                  Service Fee
                  <span class="float-end"
                    >{{ cs }}{{service_fee_amount|floatformat:2}}</span
                  >
                </p>
              </li>
              <!-- <li class="subtitle"><p>xEstimated Taxes <i data-bs-toggle="tooltip" data-bs-placement="top" title="Tooltip on top" class="bi bi-info-circle-fill"></i><span class="float-end">{{ cs }}{{total_tax|floatformat:2}}</span></p></li> -->
              <!-- <li class="subtitle"><p>Service Fee <span class="float-end">{{ cs }}{{service_fee_amount|floatformat:2}}</span></p></li> -->
              <li class="subtitle"><hr /></li>
              <li class="subtitle totals">
                <p>
                  Total
                  <span class="float-end"
                    >{{cs}}{{total_amount|floatformat:2}}</span
                  >
                </p>
              </li>

              {% if coupon_name %}
              <li><b>{{coupon_name}}</b> Coupon Applied</li>
              {% endif %} {% for item in coupon_name.items %} hi {% endfor %}
            </ul>
          </div>

          <a
            href="{% url 'store:shipping_address' %}"
            class="btn w100 mt-4 purple-btn"
            >Continue</a
          >
        </div>
      </div>
    </div>
  </section>
</div>

<script>
  $(document).on("click", "#increase-btn", function () {
    let id = $(this).attr("data-btn");
    var input_value = $("#qty" + id).val();
    console.log(input_value);

    if (input_value >= 0) {
      input_value++;
      $("#qty" + id).val(input_value);
    }
  });

  $(document).on("click", "#decrease-btn", function () {
    let id = $(this).attr("data-btn");
    var input_value = $("#qty" + id).val();
    console.log(input_value);

    if (input_value >= 0) {
      input_value--;
      $("#qty" + id).val(input_value);
    }

    if (input_value === 0) {
      $("#qty" + id).val(1);
    }
  });
</script>

{% endblock content %}

templates/store/categories.html
{% extends "partials/ffless/basestandard.html" %}
{% load static %}
{% block title %}
All Categories
{% endblock title %}
{% block content %}



<section class="top-category pb30 pt20">
   <div class="container">
      <div class="row">
         <div class="col-lg-12">
            <div class="d-flex justify-content-between">
               <div class="main-title">
                  <h2>All Categories</h2>
               </div>
            </div>
         </div>
      </div>
      <div class="row ovh">
         {% for c in categories_ %}
         <div class="col-6 col-md-3 col-xl wow fadeInUp" data-wow-duration=".7s">
            <a href="{% url 'store:category_detail' c.cid %}">
               <div class="iconbox">
                  <div class="icon"><img src="{{c.image.url}}" alt="Category Image"></div>
                  <div class="details">
                     <h5 class="title">{{c.title|title}}</h5>
                     <p class="subtitle">{{c.product_count}} item(s)</p>
                  </div>
               </div>
            </a>
         </div>
         {% endfor %}

      </div>

   </div>
</section>


{% endblock content %}